// Code generated by "stringer -type MessageType"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgPrefixLogin-2]
	_ = x[MsgPrefixDPad-3]
	_ = x[MsgPrefixRepeat-4]
	_ = x[MsgPrefixUpdateGps-5]
	_ = x[MsgPrefixUpdatePlayers-6]
	_ = x[MsgPrefixPlayerMessage-7]
	_ = x[MsgPrefixErrorMessage-8]
	_ = x[MsgPrefixBufferSize-9]
	_ = x[MsgPrefixPlayerLogoff-10]
	_ = x[MsgPrefixPing-11]
	_ = x[MsgPrefixPong-12]
}

const _MessageType_name = "MsgPrefixLoginMsgPrefixDPadMsgPrefixRepeatMsgPrefixUpdateGpsMsgPrefixUpdatePlayersMsgPrefixPlayerMessageMsgPrefixErrorMessageMsgPrefixBufferSizeMsgPrefixPlayerLogoffMsgPrefixPingMsgPrefixPong"

var _MessageType_index = [...]uint8{0, 14, 27, 42, 60, 82, 104, 125, 144, 165, 178, 191}

func (i MessageType) String() string {
	i -= 2
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i+2), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
